---
title: PdfException.PdfException
second_title: Aspose.PDF for .NET API Reference
description: PdfException 생성자. PdfException 클래스의 새 인스턴스를 초기화합니다.
type: docs
weight: 10
url: /ko/net/aspose.pdf/pdfexception/pdfexception/
---
## PdfException() {#constructor}

[`PdfException`](../) 클래스의 새 인스턴스를 초기화합니다.

```csharp
public PdfException()
```

### See Also

* class [PdfException](../)
* namespace [Aspose.Pdf](../../../aspose.pdf/)
* assembly [Aspose.PDF](../../../)

---

## PdfException(string) {#constructor_2}

[`PdfException`](../) 클래스의 새 인스턴스를 초기화합니다.

```csharp
public PdfException(string message)
```

| Parameter | Type | Description |
| --- | --- | --- |
| message | String | 메시지입니다. |

### See Also

* class [PdfException](../)
* namespace [Aspose.Pdf](../../../aspose.pdf/)
* assembly [Aspose.PDF](../../../)

---

## PdfException(string, Exception) {#constructor_3}

지정된 오류 메시지와 이 예외의 원인인 내부 예외에 대한 참조로 [`PdfException`](../) 클래스의 새 인스턴스를 초기화합니다.

```csharp
public PdfException(string message, Exception innerException)
```

| Parameter | Type | Description |
| --- | --- | --- |
| message | String | 예외의 원인을 설명하는 오류 메시지입니다. |
| innerException | Exception | 현재 예외의 원인인 예외 또는 내부 예외가 지정되지 않은 경우 null 참조(Visual Basic에서는 Nothing)입니다. |

### See Also

* class [PdfException](../)
* namespace [Aspose.Pdf](../../../aspose.pdf/)
* assembly [Aspose.PDF](../../../)

---

## PdfException(Exception) {#constructor_1}

이 예외의 원인인 내부 예외에 대한 참조로 [`PdfException`](../) 클래스의 새 인스턴스를 초기화합니다.

```csharp
public PdfException(Exception innerException)
```

| Parameter | Type | Description |
| --- | --- | --- |
| innerException | Exception | 현재 예외의 원인인 예외 또는 내부 예외가 지정되지 않은 경우 null 참조(Visual Basic에서는 Nothing)입니다. |

### See Also

* class [PdfException](../)
* namespace [Aspose.Pdf](../../../aspose.pdf/)
* assembly [Aspose.PDF](../../../)