---
title: PdfException
second_title: Aspose.PDF for Java API Reference
description: Represents errors that occur during PDF application execution.
type: docs
weight: 31
url: /java/com.aspose.pdf.exceptions/pdfexception/
---
**Inheritance:**
java.lang.Object, java.lang.Throwable, java.lang.Exception, java.lang.RuntimeException, com.aspose.ms.System.Exception, com.aspose.ms.System.ApplicationException
```
public class PdfException extends System.ApplicationException
```

Represents errors that occur during PDF application execution.
## Constructors

| Constructor | Description |
| --- | --- |
| [PdfException()](#PdfException--) | Initializes a new instance of the  PdfException  class. |
| [PdfException(String message)](#PdfException-java.lang.String-) | Initializes a new instance of the  PdfException  class. |
| [PdfException(String message, Throwable innerException)](#PdfException-java.lang.String-java.lang.Throwable-) | Initializes a new instance of the  PdfException  class with a specified error message and a reference to the inner exception that is the cause of this exception. |
### PdfException() {#PdfException--}
```
public PdfException()
```


Initializes a new instance of the  PdfException  class.

### PdfException(String message) {#PdfException-java.lang.String-}
```
public PdfException(String message)
```


Initializes a new instance of the  PdfException  class.

**Parameters:**
| Parameter | Type | Description |
| --- | --- | --- |
| message | java.lang.String | The message. |

### PdfException(String message, Throwable innerException) {#PdfException-java.lang.String-java.lang.Throwable-}
```
public PdfException(String message, Throwable innerException)
```


Initializes a new instance of the  PdfException  class with a specified error message and a reference to the inner exception that is the cause of this exception.

**Parameters:**
| Parameter | Type | Description |
| --- | --- | --- |
| message | java.lang.String | The error message that explains the reason for the exception. |
| innerException | java.lang.Throwable | The exception that is the cause of the current exception, or a null reference |

