---
title: SanitizationException.SanitizationException
second_title: Aspose.PDF for .NET API Reference
description: Конструктор SanitizationException. Инициализирует новый экземпляр класса SanitizationException
type: docs
weight: 10
url: /ru/net/aspose.pdf.sanitization/sanitizationexception/sanitizationexception/
---
## SanitizationException() {#constructor}

Инициализирует новый экземпляр класса [`SanitizationException`](../).

```csharp
public SanitizationException()
```

### See Also

* class [SanitizationException](../)
* namespace [Aspose.Pdf.Sanitization](../../../aspose.pdf.sanitization/)
* assembly [Aspose.PDF](../../../)

---

## SanitizationException(string) {#constructor_2}

Инициализирует новый экземпляр класса [`SanitizationException`](../).

```csharp
public SanitizationException(string message)
```

| Parameter | Type | Description |
| --- | --- | --- |
| message | String | Сообщение. |

### See Also

* class [SanitizationException](../)
* namespace [Aspose.Pdf.Sanitization](../../../aspose.pdf.sanitization/)
* assembly [Aspose.PDF](../../../)

---

## SanitizationException(string, Exception) {#constructor_3}

Инициализирует новый экземпляр класса [`SanitizationException`](../) с указанным сообщением об ошибке и ссылкой на внутреннее исключение, которое является причиной этого исключения.

```csharp
public SanitizationException(string message, Exception innerException)
```

| Parameter | Type | Description |
| --- | --- | --- |
| message | String | Сообщение об ошибке, которое объясняет причину исключения. |
| innerException | Exception | Исключение, которое является причиной текущего исключения, или ссылка null (Nothing в Visual Basic), если внутреннее исключение не указано. |

### See Also

* class [SanitizationException](../)
* namespace [Aspose.Pdf.Sanitization](../../../aspose.pdf.sanitization/)
* assembly [Aspose.PDF](../../../)

---

## SanitizationException(Exception) {#constructor_1}

Инициализирует новый экземпляр класса [`SanitizationException`](../) с указанным сообщением об ошибке и ссылкой на внутреннее исключение, которое является причиной этого исключения.

```csharp
public SanitizationException(Exception innerException)
```

| Parameter | Type | Description |
| --- | --- | --- |
| innerException | Exception | Исключение, которое является причиной текущего исключения, или ссылка null (Nothing в Visual Basic), если внутреннее исключение не указано. |

### See Also

* class [SanitizationException](../)
* namespace [Aspose.Pdf.Sanitization](../../../aspose.pdf.sanitization/)
* assembly [Aspose.PDF](../../../)